
monolith_module.user.index:
    path: /
    defaults:
        _controller: UserModuleBundle:User:index

monolith_module.user.edit:
    path: /edit
    defaults:
        _controller: UserModuleBundle:User:edit

monolith_module.user.change-password:
    path: /change-password
    defaults:
        _controller: UserModuleBundle:User:changePassword

# Resetting password
monolith_module.user.resetting:
    path: /resetting/
    defaults:
        _controller: UserModuleBundle:User:resettingRequest

monolith_module.user.resetting.send-email:
    path: /resetting/send-email
    defaults:
        _controller: FOSUserBundle:Resetting:sendEmail

monolith_module.user.resetting.check-email:
    path: /resetting/check-email
    defaults:
        _controller: FOSUserBundle:Resetting:checkEmail

monolith_module.user.resetting.reset:
    path: /resetting/reset/{token}
    defaults:
        _controller: FOSUserBundle:Resetting:reset

# Registration
monolith_module.user.registration:
    path: /register/
    defaults:
        _controller: UserModuleBundle:User:register

monolith_module.user.registration.check-email:
    path: /register/check-email
    defaults:
        _controller: UserModuleBundle:User:registerCheckEmail

monolith_module.user.registration.confirm:
    path: /register/confirm/{token}
    defaults:
        _controller: FOSUserBundle:Registration:confirm

monolith_module.user.registration.confirmed:
    path: /register/confirmed
    defaults:
        _controller: FOSUserBundle:Registration:confirmed
